/**
 * MASQUERADE · The 40 guests.
 *
 * Ported verbatim from docs/CHARACTERS.md. Order matches the doc:
 *   Royalty (1-8) · Thief (9-16) · Scholar (17-24) · Hunter (25-32) · Mystic (33-40)
 *
 * Two icons in the source doc fall outside the canonical 5-icon set defined in
 * types.ts ('moon' | 'day' | 'water' | 'feather' | 'rose'):
 *   - #25 라오나 궁수 uses 🏹 (bow). Reassigned to 'day' (☀️) — matches her
 *     "초원의 딸 / 사냥 대회 우승" open-field daytime imagery.
 *   - #34 수정구의 노인 uses 🌫 (fog). Reassigned to 'water' (🌊) — mist is
 *     water vapor and "안개의 아버지" ties naturally to canal fog.
 * Both reinterpretations flagged in the port report.
 */

import type { Card, Identity } from './types.ts'

export const DECK_SIZE = 40

export const CARDS: readonly Card[] = [
  // 👑 왕족 · Corte (1-8)
  {
    id: 1,
    name: '가스통 자작',
    shadowName: '젊은 늑대',
    identity: 'Royalty',
    surface: 3,
    number: 1,
    icon: 'day',
    whisper: false,
    flavor: '백작가의 젊은 후계자, 야심 있음',
  },
  {
    id: 2,
    name: '붉은 나비 부인',
    shadowName: '왕비의 그림자',
    identity: 'Royalty',
    surface: 4,
    number: 2,
    icon: 'rose',
    whisper: true,
    flavor: '왕비의 사촌, 왕궁 정보에 밝음',
  },
  {
    id: 3,
    name: '말콤 백작',
    shadowName: '회색 사자',
    identity: 'Royalty',
    surface: 2,
    number: 3,
    icon: 'feather',
    whisper: false,
    flavor: '노장 백작, 3대 왕을 섬김',
  },
  {
    id: 4,
    name: '이자벨라 공녀',
    shadowName: '겨울 장미',
    identity: 'Royalty',
    surface: 4,
    number: 4,
    icon: 'rose',
    whisper: false,
    flavor: '왕의 조카, 정치적으로 순진',
  },
  {
    id: 5,
    name: '은빛 여우 남작',
    shadowName: '여명의 사냥꾼',
    identity: 'Royalty',
    surface: 3,
    number: 5,
    icon: 'day',
    whisper: false,
    flavor: '신흥 귀족, 상승 야망 강함',
  },
  {
    id: 6,
    name: '마리에르 공주',
    shadowName: '별의 딸',
    identity: 'Royalty',
    surface: 4,
    number: 6,
    icon: 'moon',
    whisper: true,
    flavor: '왕녀 · 예언에 관심 있음',
  },
  {
    id: 7,
    name: '레오나르 자작',
    shadowName: '젊은 매',
    identity: 'Royalty',
    surface: 2,
    number: 7,
    icon: 'feather',
    whisper: false,
    flavor: '왕궁 근위대 대장의 아들',
  },
  {
    id: 8,
    name: '루이자 백작부인',
    shadowName: '아침의 여인',
    identity: 'Royalty',
    surface: 3,
    number: 8,
    icon: 'day',
    whisper: false,
    flavor: '왕비의 시녀장',
  },

  // 🗡 도둑 · Ombra (9-16)
  {
    id: 9,
    name: '카를로 자객',
    shadowName: '밤의 손',
    identity: 'Thief',
    surface: 2,
    number: 9,
    icon: 'moon',
    whisper: true,
    flavor: '조용한 암살자, 왕궁 침투 전문',
  },
  {
    id: 10,
    name: '은침 부인',
    shadowName: '회색 나비',
    identity: 'Thief',
    surface: 1,
    number: 10,
    icon: 'rose',
    whisper: false,
    flavor: '늙은 정보상, 30년 왕궁 지켜봄',
  },
  {
    id: 11,
    name: '미스터리 손님',
    shadowName: '이름 없는 자',
    identity: 'Thief',
    surface: 3,
    number: 11,
    icon: 'feather',
    whisper: false,
    flavor: '정체 불명 (모두 도둑이라고만 알아)',
  },
  {
    id: 12,
    name: '라파엘 남작',
    shadowName: '은화 상인',
    identity: 'Thief',
    surface: 2,
    number: 12,
    icon: 'water',
    whisper: false,
    flavor: '표면은 상인 · 실체는 밀수 왕',
  },
  {
    id: 13,
    name: '그림자 자객',
    shadowName: '검은 물결',
    identity: 'Thief',
    surface: 1,
    number: 13,
    icon: 'water',
    whisper: true,
    flavor: '운하를 통해 침투하는 자',
  },
  {
    id: 14,
    name: '실비아 부인',
    shadowName: '뱀의 미소',
    identity: 'Thief',
    surface: 3,
    number: 14,
    icon: 'rose',
    whisper: false,
    flavor: '궁정 스캔들 전문, 정보 판매',
  },
  {
    id: 15,
    name: '어둠의 사도',
    shadowName: '조용한 검',
    identity: 'Thief',
    surface: 2,
    number: 15,
    icon: 'moon',
    whisper: false,
    flavor: '검은 옷의 왕궁 침입자',
  },
  {
    id: 16,
    name: '마르티노 도둑',
    shadowName: '회색 그림자',
    identity: 'Thief',
    surface: 1,
    number: 16,
    icon: 'feather',
    whisper: false,
    flavor: '왕궁 서고 침입 이력 있음',
  },

  // 📚 학자 · Sapienza (17-24)
  {
    id: 17,
    name: '알베르토 신관',
    shadowName: '은발의 예지자',
    identity: 'Scholar',
    surface: 2,
    number: 17,
    icon: 'feather',
    whisper: false,
    flavor: '왕궁 도서관 사서 40년',
  },
  {
    id: 18,
    name: '별관측대의 노인',
    shadowName: '하늘 읽는 자',
    identity: 'Scholar',
    surface: 3,
    number: 18,
    icon: 'moon',
    whisper: false,
    flavor: '왕궁 천문관 · 예언 부정론자',
  },
  {
    id: 19,
    name: '잊혀진 신관',
    shadowName: '지워진 이름',
    identity: 'Scholar',
    surface: 2,
    number: 19,
    icon: 'feather',
    whisper: true,
    flavor: '이단으로 지목되어 숨는 학자',
  },
  {
    id: 20,
    name: '이반 남작',
    shadowName: '두꺼운 안경',
    identity: 'Scholar',
    surface: 4,
    number: 20,
    icon: 'water',
    whisper: false,
    flavor: '화학과 연금술 전문 (합리주의)',
  },
  {
    id: 21,
    name: '오래된 도서관 지기',
    shadowName: '먼지의 수호자',
    identity: 'Scholar',
    surface: 1,
    number: 21,
    icon: 'feather',
    whisper: false,
    flavor: '800년 도서관에서 살아온 인물',
  },
  {
    id: 22,
    name: '세비녜 부인',
    shadowName: '검은 잉크',
    identity: 'Scholar',
    surface: 3,
    number: 22,
    icon: 'rose',
    whisper: false,
    flavor: '왕궁 연대기 저자 · 스캔들 기록',
  },
  {
    id: 23,
    name: '뮤리엘 학자',
    shadowName: '은빛 로브',
    identity: 'Scholar',
    surface: 2,
    number: 23,
    icon: 'day',
    whisper: false,
    flavor: '젊은 대학자 · 새 이론 발표',
  },
  {
    id: 24,
    name: '침묵의 사서',
    shadowName: '잃어버린 책',
    identity: 'Scholar',
    surface: 2,
    number: 24,
    icon: 'moon',
    whisper: true,
    flavor: '사라진 왕궁 기록의 유일 목격자',
  },

  // 🏹 사냥꾼 · Caccia (25-32)
  {
    id: 25,
    name: '라오나 궁수',
    shadowName: '초원의 딸',
    identity: 'Hunter',
    surface: 3,
    // Source doc icon 🏹 falls outside canonical 5-icon set.
    // Reassigned to 'day' — matches open-field/daytime hunt imagery.
    number: 25,
    icon: 'day',
    whisper: false,
    flavor: '여성 궁수 · 왕궁 사냥 대회 우승',
  },
  {
    id: 26,
    name: '침묵의 궁수',
    shadowName: '그림자 화살',
    identity: 'Hunter',
    surface: 2,
    number: 26,
    icon: 'moon',
    whisper: true,
    flavor: '이름 없는 저격수',
  },
  {
    id: 27,
    name: '파울로 사냥대장',
    shadowName: '늙은 사자',
    identity: 'Hunter',
    surface: 4,
    number: 27,
    icon: 'day',
    whisper: false,
    flavor: '근위대 사냥 대장 · 20년 경력',
  },
  {
    id: 28,
    name: '아만다 궁수',
    shadowName: '붉은 매',
    identity: 'Hunter',
    surface: 3,
    number: 28,
    icon: 'rose',
    whisper: false,
    flavor: '여왕 근위대 · 왕비 개인 경호',
  },
  {
    id: 29,
    name: '숲의 부인',
    shadowName: '이끼 왕관',
    identity: 'Hunter',
    surface: 2,
    number: 29,
    icon: 'feather',
    whisper: false,
    flavor: '왕궁 사냥터 관리인의 딸',
  },
  {
    id: 30,
    name: '마르코 사냥꾼',
    shadowName: '검은 늑대',
    identity: 'Hunter',
    surface: 2,
    number: 30,
    icon: 'moon',
    whisper: false,
    flavor: '늑대 사냥 전문 · 무언',
  },
  {
    id: 31,
    name: '은빛 매 부인',
    shadowName: '하늘의 눈',
    identity: 'Hunter',
    surface: 3,
    number: 31,
    icon: 'day',
    whisper: true,
    flavor: '매 조련사 · 왕궁 매사냥 총관',
  },
  {
    id: 32,
    name: '조용한 궁수',
    shadowName: '침묵의 화살',
    identity: 'Hunter',
    surface: 1,
    number: 32,
    icon: 'water',
    whisper: false,
    flavor: '운하 근처 사냥꾼',
  },

  // 🔮 신비주의자 · Mistero (33-40)
  {
    id: 33,
    name: '루비아나 백작부인',
    shadowName: '별 읽는 자',
    identity: 'Mystic',
    surface: 4,
    number: 33,
    icon: 'moon',
    whisper: false,
    flavor: '궁정 예언자 · 왕에게 조언',
  },
  {
    id: 34,
    name: '수정구의 노인',
    shadowName: '안개의 아버지',
    identity: 'Mystic',
    surface: 3,
    // Source doc icon 🌫 (fog) falls outside canonical 5-icon set.
    // Reassigned to 'water' — mist/fog is water vapor; ties to canal fog.
    number: 34,
    icon: 'water',
    whisper: true,
    flavor: '은둔 마술사 · 30년만에 등장',
  },
  {
    id: 35,
    name: '세라피나 부인',
    shadowName: '라벤더 마녀',
    identity: 'Mystic',
    surface: 3,
    number: 35,
    icon: 'rose',
    whisper: false,
    flavor: '향수 마술사 · 왕비 애용',
  },
  {
    id: 36,
    name: '마르코 예언자',
    shadowName: '미래의 목소리',
    identity: 'Mystic',
    surface: 2,
    number: 36,
    icon: 'feather',
    whisper: false,
    flavor: '젊은 예언자 · 최근 등장',
  },
  {
    id: 37,
    name: '은하수 카드사',
    shadowName: '별지도 손',
    identity: 'Mystic',
    surface: 4,
    number: 37,
    icon: 'moon',
    whisper: false,
    flavor: '타로 마스터 · 무도회에서 첫 등장',
  },
  {
    id: 38,
    name: '안개의 여인',
    shadowName: '형체 없는 자',
    identity: 'Mystic',
    surface: 2,
    number: 38,
    icon: 'water',
    whisper: true,
    flavor: '실체 논란 · 그림자만 보임',
  },
  {
    id: 39,
    name: '검은 로브 사도',
    shadowName: '어둠의 눈',
    identity: 'Mystic',
    surface: 3,
    number: 39,
    icon: 'moon',
    whisper: false,
    flavor: '이단으로 몰림 · 궁정에서 밀려남',
  },
  {
    id: 40,
    name: '미스티코 형제',
    shadowName: '두 얼굴의 자',
    identity: 'Mystic',
    surface: 1,
    number: 40,
    icon: 'day',
    whisper: false,
    flavor: '쌍둥이 마술사 · 정체성 모호',
  },
] as const

/** Look up a card by numeric id (1..40). Throws for unknown ids. */
export function cardById(id: number): Card {
  const card = CARDS.find((c) => c.id === id)
  if (!card) throw new Error(`cardById: no card with id=${id}`)
  return card
}

/** Filter cards by identity. */
export function cardsByIdentity(id: Identity): Card[] {
  return CARDS.filter((c) => c.identity === id)
}
